name: Release on Push to Main

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'CHANGELOG.md'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  check-version:
    name: Check if Version Changed
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check.outputs.changed }}
      new_version: ${{ steps.check.outputs.new_version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get new version
        id: new
        run: |
          NEW_VERSION=$(grep '"version"' package.json | head -1 | sed -E 's/.*"version": "([^"]+)".*/\1/')
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
      
      - name: Get old version
        id: old
        run: |
          OLD_VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.0.0")
          echo "old_version=$OLD_VERSION" >> $GITHUB_OUTPUT
      
      - name: Compare versions
        id: check
        run: |
          NEW_VERSION=${{ steps.new.outputs.new_version }}
          OLD_VERSION=${{ steps.old.outputs.old_version }}
          if [ "$NEW_VERSION" != "$OLD_VERSION" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Version changed: $OLD_VERSION to $NEW_VERSION"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  create-release:
    name: Create GitHub Release
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check-version.outputs.new_version }}
          release_name: Release v${{ needs.check-version.outputs.new_version }}
          draft: false
          prerelease: false

  publish-npm:
    name: Publish to NPM
    needs:
      - check-version
      - create-release
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: https://registry.npmjs.org
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Build package
        run: npm run build --if-present
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}